// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACMBtcWev6PauORIlD03oA9cwhN-HJF9Q',
    appId: '1:724080536150:web:1ea7d6af4066cb96dde9f7',
    messagingSenderId: '724080536150',
    projectId: 'skinai-b364f',
    authDomain: 'skinai-b364f.firebaseapp.com',
    databaseURL: 'https://skinai-b364f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skinai-b364f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvr1LsBhYKCUqjShp9iYh54DH2_ubi7Xw',
    appId: '1:724080536150:android:87707f63be67bfcfdde9f7',
    messagingSenderId: '724080536150',
    projectId: 'skinai-b364f',
    databaseURL: 'https://skinai-b364f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skinai-b364f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdHbX0TFQL0g6UbUIYW5ATwDV_xdXiuIU',
    appId: '1:724080536150:ios:ffc1bc7354889b47dde9f7',
    messagingSenderId: '724080536150',
    projectId: 'skinai-b364f',
    databaseURL: 'https://skinai-b364f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skinai-b364f.firebasestorage.app',
    iosClientId: '724080536150-0ge4ha4lg4loe5331sm24t663mjj87o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdHbX0TFQL0g6UbUIYW5ATwDV_xdXiuIU',
    appId: '1:724080536150:ios:ffc1bc7354889b47dde9f7',
    messagingSenderId: '724080536150',
    projectId: 'skinai-b364f',
    databaseURL: 'https://skinai-b364f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skinai-b364f.firebasestorage.app',
    iosClientId: '724080536150-0ge4ha4lg4loe5331sm24t663mjj87o7.apps.googleusercontent.com',
    iosBundleId: 'com.example.skinApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACMBtcWev6PauORIlD03oA9cwhN-HJF9Q',
    appId: '1:724080536150:web:8aec843cb5698afddde9f7',
    messagingSenderId: '724080536150',
    projectId: 'skinai-b364f',
    authDomain: 'skinai-b364f.firebaseapp.com',
    databaseURL: 'https://skinai-b364f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'skinai-b364f.firebasestorage.app',
  );
}
